version: "3.9"
services:
  jbook-app:
    container_name: jbook-app
    image: jbook-app:1.0
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"